env_file:
  - .env.staging

services:
  vue:
    build:
      context: .
      dockerfile: compose/staging/Dockerfile
      args:
        VITE_ENVIRONMENT: ${VITE_ENVIRONMENT}
        VITE_BASE_URL: ${VITE_BASE_URL}
        VITE_STRIPE_PUBLISHABLE_KEY: ${VITE_STRIPE_PUBLISHABLE_KEY}
    ports:
      - 8080:80

